kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sidecar-job-controller
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["delete", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create", "get"]
