kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: sidecar-job-controller
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: sidecar-job-controller
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: sidecar-job-controller
